### ISSUE TITLE
SQL permissions issue when using vagrant setup

### ISSUE THREAD

**Issue by webervin** [depesz/explain.depesz.com#7]
followed steps in https://github.com/depesz/explain.depesz.com#vagrant-setup, ended up with  SQL error when posting first plan to local service:

```
2017-04-13 07:47:05 UTC ERROR:  permission denied for schema plans at character 13
2017-04-13 07:47:05 UTC QUERY:  INSERT INTO plans."part_O" (id, title, plan, is_public, entered_on, is_anonymized, delete_key, added_by) VALUES ($1, $2, $3, $4, no
w(), $5, $6, $7 )
2017-04-13 07:47:05 UTC CONTEXT:  PL/pgSQL function register_plan(text,text,boolean,boolean,text) line 12 at EXECUTE statement
2017-04-13 07:47:05 UTC STATEMENT:  SELECT id, delete_key FROM register_plan('', '"my plan here)"
```

my environment was as follows:
```
:~/explain.depesz.com$ git show
commit e289a74ccb0f7477868fc7e448ec46bb58eb07d0

~/explain.depesz.com$ vagrant version
Installed Version: 1.9.1
Latest Version: 1.9.3

~/explain.depesz.com$ uname -a
Linux boxname 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
~/explain.depesz.com$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by depesz** [comment]
Sorry, I have literally zero knowledge about vagrant. It looks that your tables were created by different user than the one that you are using from explain app to connect to the database from. No idea how to change it in vagrant, but  in psql, it's as simple as:

alter table <name> set owner to <some_user>;

If you can fix vagrant setup - I'll gladly include the patch, otherwise we can wait for @pkorobeinikov to chime in - maybe he knows what's up.

**Comment by webervin** [comment]
note: i also have no vagrant knowledge, just grep'ed GRANT's in configs.

**Comment by depesz** [comment]
Thanks a lot. I Assumed you tested it, and it solved the problem for you.
